name: Test
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
        with:
          name: devenv
      - name: Test Bash Shell with Local and External Flakes
        uses: workflow/nix-shell-action@v3
        with:
          script: |
            pwd
            nix run .#
